version: "2"
  
services:
  rsnapshot:
    image: helmuthb/rsnapshot
    restart: always
    privileged: true
    container_name: #<NameofContainer>
    volumes:
      # - /homedirectory/backup.cfg:/backup.cfg
      # - /homedirectory/smb_mount.sh:/smb/smb_mount.sh
      # - /homedirectory/smb_umount.sh:/smb/smb_umount.sh
      # - /mnt/Backup/datosBackup:/backup
      # - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
    environment:
      # - BACKUP_NAME=<Name of the backup>
      # - CRON_DAILY= * * * * *
      # - CRON_WEEKLY= * * * * *
      # - CRON_MONTHLY= * * * * *
      # - BACKUP_HOURLY=0
      # - BACKUP_DAILY=7
      # - BACKUP_WEEKLY=4
      # - BACKUP_MONTHLY=3

